Repository BinaryStudioAcademy/bsa-2021-slidez, pull requests merged in 2021-09, with the labels that each got.

#170 Sync frontend and backend password validation
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/auth/jwtauth/validation/AuthorizationRequestValidator.java
Labels: bug, Approved

#167 notification bug fix, render refactor
  slidez-fe-core/src/common/components/forms/LoginForm.tsx
  slidez-fe-core/src/services/auth/auth-service.ts
Labels: bug, Approved

#169 Added deleting user, updated entities to fetch user lazily, created c…
  slidez-core/src/main/java/com/binarystudio/academy/slidez/app/user/UserController.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/auth/oauth2/model/GoogleCredentials.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/poll/model/Poll.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/qasession/model/QASession.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/quiz/model/Quiz.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/user/UserRepository.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/user/UserService.java
  slidez-core/src/main/resources/db/migration/V16__add_cascade_properties_to_owner_id.sql
  slidez-fe-core/src/containers/user-menu/UserMenu.tsx
  slidez-fe-core/src/containers/user/store.ts
  slidez-fe-core/src/services/user/user-service.ts
  slidez-shared/src/net/http/http-helper.ts
Labels: enhancement, Approved

#173 fix/169-highlighted_in_red_fields_log_in
  slidez-fe-core/src/common/components/forms/LoginForm.tsx
Labels: bug

#168 Added ability to handle and propagate "Add reaction" event
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/interactive_element/model/InteractiveElementType.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionPoll.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionReaction.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/enums/ResponseType.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/enums/SessionPollStatus.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/enums/SessionReactionType.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/AddReactionEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/AddReactionEventHandler.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/HandlerChainHolder.java
Labels: enhancement, Approved

#175 fix/replace get data by token to get by principal
  slidez-core/src/main/java/com/binarystudio/academy/slidez/app/user/UserController.java
  slidez-fe-core/src/common/components/forms/LoginForm.tsx
  slidez-fe-core/src/containers/user/store.ts
  slidez-fe-core/src/pages/dashboard/Dashboard.tsx
  slidez-fe-core/src/services/auth/auth-service.ts
  slidez-fe-core/src/services/auth/dto/TokenDto.ts
  slidez-fe-core/src/services/user/user-service.ts
Labels: bug

#183 Fix user avatar
  slidez-fe-core/src/containers/user-menu/styles.module.scss
  slidez-fe-core/src/pages/dashboard/styles.module.scss
Labels: bug

#180 Setup Presenter-Participant flow
  slidez-core/src/main/java/com/binarystudio/academy/slidez/app/presentation/PresentationController.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/presentation/PresentationService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/presentation/dto/PresentationSessionDTO.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/PresentationEventStore.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/SessionRepository.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/SessionService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/snapshot/SimpleSnapshot.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/snapshot/Snapshot.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/infrastructure/security/SecurityConfig.java
  slidez-extension/.env.development
  slidez-extension/src/background.ts
  slidez-extension/src/chrome-store.ts
  slidez-extension/src/env.ts
  slidez-extension/src/present-mode/current-slide-watcher/current-slide-watcher.tsx
  slidez-extension/src/present-mode/present-mode.ts
  slidez-fe-core/package.json
  slidez-fe-core/src/App.tsx
  slidez-fe-core/src/common/components/forms/LoginForm.tsx
  slidez-fe-core/src/common/components/interactive-elements/interactive-wrapper/interactive-wrapper.scss
  slidez-fe-core/src/common/components/interactive-elements/poll/ParticipantPoll.tsx
  slidez-fe-core/src/common/components/interactive-elements/poll/Poll.tsx
  slidez-fe-core/src/common/components/interactive-elements/poll/PollInput.scss
  slidez-fe-core/src/common/components/interactive-elements/poll/PollInput.tsx
  slidez-fe-core/src/common/components/interactive-elements/poll/PresenterPoll.tsx
  slidez-fe-core/src/common/components/interactive-elements/poll/presenterPoll.scss
  slidez-fe-core/src/common/routes/app-route.ts
  slidez-fe-core/src/containers/poll-editor/Addon.tsx
  slidez-fe-core/src/containers/poll-editor/store/index.ts
  slidez-fe-core/src/containers/session/Session.tsx
  slidez-fe-core/src/containers/session/dto/SnapshotDto.ts
  slidez-fe-core/src/containers/session/enums/ws-connection-status.ts
  slidez-fe-core/src/containers/session/session.scss
  slidez-fe-core/src/containers/session/store/responseHandler.ts
  slidez-fe-core/src/containers/session/store/store.ts
  slidez-fe-core/src/pages/event/EventPage.tsx
  slidez-fe-core/src/pages/event/ParticipantView.tsx
  slidez-fe-core/src/pages/event/styles.scss
  slidez-fe-core/src/pages/interactive/Header.tsx
  slidez-fe-core/src/pages/interactive/NoEventPage.tsx
  slidez-fe-core/src/pages/interactive/common.scss
  slidez-fe-core/src/pages/interactive/header.scss
  slidez-fe-core/src/pages/interactive/noEvent.scss
  slidez-fe-core/src/pages/interactive/participant/EventItem.tsx
  slidez-fe-core/src/pages/interactive/participant/ParticipantNameModal.tsx
  slidez-fe-core/src/pages/interactive/participant/ParticipantPage.tsx
  slidez-fe-core/src/pages/interactive/participant/ParticipantView.tsx
  slidez-fe-core/src/pages/interactive/participant/participantPage.scss
  slidez-fe-core/src/pages/interactive/participant/participantView.scss
  slidez-fe-core/src/pages/interactive/presenter/PresenterPage.tsx
  slidez-fe-core/src/pages/interactive/presenter/presenterPage.scss
  slidez-fe-core/src/pages/participant-page/ParticipantPage.tsx
  slidez-fe-core/src/pages/participant-page/mock-data.ts
  slidez-fe-core/src/services/participant-event/dto/ParticipantEvent.ts
  slidez-fe-core/src/services/participant-event/participant-event-service.ts
  slidez-fe-core/src/services/participant/dto/ParticipantData.ts
  slidez-fe-core/src/services/participant/participant-service.ts
  slidez-fe-core/tsconfig.json
  slidez-fe-core/yarn.lock
  slidez-shared/src/event-bus/protocol/index.ts
Labels: enhancement

#185 feature/179-max-height_for_list_of_polls_on_addon
  slidez-fe-core/src/containers/poll-editor/Menu.scss
  slidez-fe-core/src/containers/poll-editor/Menu.tsx
Labels: enhancement

#184 fix/delete red highlighted after filling valid data
  slidez-fe-core/src/containers/user/store.ts
Labels: bug, Approved

#188 add asterisk to required fields
  slidez-fe-core/src/containers/user-menu/edit-profile/components/Form.scss
  slidez-fe-core/src/containers/user-menu/edit-profile/components/FormUpdateUserData.tsx
Labels: Approved

#187 Feature/145 add tooltips side menu
  slidez-fe-core/src/containers/sideBar/SideBar.tsx
  slidez-fe-core/src/containers/sideBar/styles.module.scss
Labels: Approved

#186 Feature/238 side menu icons effects
  slidez-fe-core/src/assets/svgs/create_presentation.svg
  slidez-fe-core/src/assets/svgs/graph_icon.svg
  slidez-fe-core/src/assets/svgs/layout_icon.svg
  slidez-fe-core/src/assets/svgs/my_presentation.svg
  slidez-fe-core/src/assets/svgs/soon.svg
  slidez-fe-core/src/assets/svgs/soon_lable.svg
  slidez-fe-core/src/containers/poll-editor/PollEditor.tsx
  slidez-fe-core/src/containers/sideBar/SideBar.tsx
  slidez-fe-core/src/containers/sideBar/styles.module.scss
Labels: Approved

#198 fix/164,226-fix_position_logo_and_search
  slidez-fe-core/src/containers/user-menu/styles.module.scss
  slidez-fe-core/src/pages/dashboard/styles.module.scss
Labels: bug

#201 fix/262-Fix_loader_on_presenter_page
  slidez-fe-core/src/common/components/loader/Loader.scss
  slidez-fe-core/src/containers/user-menu/edit-profile/components/Loader.scss
  slidez-fe-core/src/containers/user-menu/edit-profile/components/Loader.tsx
Labels: bug

#195 Feature/241 on adding poll to presentation deal with correct and incorrect adding
  slidez-fe-core/src/containers/poll-editor/Menu.scss
  slidez-fe-core/src/containers/poll-editor/Menu.tsx
  slidez-fe-core/src/containers/poll-editor/PollEditor.tsx
  slidez-fe-core/src/containers/poll-editor/store/index.ts
Labels: bug

#205 Feature/q and a communication
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/presentation/PresentationRepository.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/presentation/PresentationService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/qasession/QASessionService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/SessionRepository.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/SessionService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQAQuestion.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/State.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/DomainEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/StartQASessionEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/StartQASessionHandler.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/snapshot/SimpleSnapshot.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/snapshot/Snapshot.java
  slidez-fe-core/src/containers/session/dto/AskQuestionDto.ts
  slidez-fe-core/src/containers/session/dto/InteractiveElement.ts
  slidez-fe-core/src/containers/session/dto/QASessionQuestionDto.ts
  slidez-fe-core/src/containers/session/dto/SessionResponse.ts
  slidez-fe-core/src/containers/session/dto/SnapshotDto.ts
  slidez-fe-core/src/containers/session/enums/SessionResponse.ts
  slidez-fe-core/src/containers/session/event/DomainEvent.ts
  slidez-fe-core/src/containers/session/event/FrontendEvent.ts
  slidez-fe-core/src/containers/session/store/responseHandler.ts
  slidez-fe-core/src/containers/session/store/selectors.ts
  slidez-fe-core/src/containers/session/store/store.ts
  slidez-fe-core/src/pages/interactive/presenter/PresenterPage.tsx
  slidez-fe-core/src/pages/qa/Qa.tsx
  slidez-fe-core/src/pages/qa/components/CloseButton.tsx
  slidez-fe-core/src/pages/qa/components/QAAdd.tsx
  slidez-fe-core/src/pages/qa/components/QACard.scss
  slidez-fe-core/src/pages/qa/components/QACard.tsx
  slidez-fe-core/src/pages/qa/mock-poll-data.ts
  slidez-fe-core/src/pages/qa/qa.scss
  slidez-fe-core/src/services/auth/auth-service.ts
  slidez-fe-core/src/services/participant/participant-service.ts
Labels: enhancement

#207 Feature/q and a likes
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQAQuestionLike.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQASession.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/State.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/enums/ResponseType.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/DomainEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/LikeQuestionEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/HandlerChainHolder.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/LikeQuestionEventHandler.java
  slidez-fe-core/src/containers/session/dto/LikeQuestionDto.ts
  slidez-fe-core/src/containers/session/dto/SessionResponse.ts
  slidez-fe-core/src/containers/session/enums/SessionResponse.ts
  slidez-fe-core/src/containers/session/event/DomainEvent.ts
  slidez-fe-core/src/containers/session/event/FrontendEvent.ts
  slidez-fe-core/src/containers/session/store/responseHandler.ts
  slidez-fe-core/src/containers/session/store/store.ts
  slidez-fe-core/src/pages/qa/Qa.tsx
Labels: enhancement

#214 Fixed creation of Session if Q&A does not exist
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/qasession/QASessionService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/StartQASessionHandler.java
  slidez-fe-core/src/containers/session/store/responseHandler.ts
Labels: bug

#216 Introduced question visibility feature
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQAQuestion.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQAQuestionVisibility.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQASession.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/State.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/enums/ResponseType.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/DomainEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/SetQuestionVisibilityEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/HandlerChainHolder.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/SetQuestionVisibilityEventHandler.java
  slidez-fe-core/src/containers/session/dto/QASessionQuestionDto.ts
  slidez-fe-core/src/containers/session/dto/QuestionVisibilityDto.ts
  slidez-fe-core/src/containers/session/dto/SessionResponse.ts
  slidez-fe-core/src/containers/session/enums/SessionResponse.ts
  slidez-fe-core/src/containers/session/event/DomainEvent.ts
  slidez-fe-core/src/containers/session/event/FrontendEvent.ts
  slidez-fe-core/src/containers/session/store/responseHandler.ts
  slidez-fe-core/src/containers/session/store/store.ts
  slidez-fe-core/src/pages/qa/Qa.tsx
Labels: enhancement

#212 Fix/252-Fix_the_user's_First_Name_display_after_registration_via_Google
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/auth/oauth2/OAuthService.java
Labels: bug

#219 Feature/moderator page
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQAQuestionVisibility.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQASession.java
  slidez-fe-core/src/App.tsx
  slidez-fe-core/src/common/routes/app-route.ts
  slidez-fe-core/src/containers/sideBar/SideBar.tsx
  slidez-fe-core/src/pages/qa/Qa.tsx
  slidez-fe-core/src/pages/qa/QuestionModeration.tsx
  slidez-fe-core/src/pages/qa/components/ModerationQACard.tsx
  slidez-fe-core/src/pages/qa/components/ModerationSelectorPanel.tsx
  slidez-fe-core/src/pages/qa/components/QACard.scss
  slidez-fe-core/src/pages/qa/components/SelectorPanel.scss
  slidez-fe-core/src/pages/qa/qa.scss
  slidez-fe-core/src/pages/qa/styles.module.scss
  slidez-fe-core/src/pages/qa/utils/sorting-utils.ts
Labels: enhancement

#210 fix/285-on-entering-event-which-doesnt-exist-frontend-crashes
  slidez-fe-core/src/containers/session/store/responseHandler.ts
Labels: bug

#225 Fixed bug with "Wait for presenter to show next slide"
  slidez-fe-core/src/services/session/session-service.ts
  slidez-fe-core/src/services/ws/ws-helper.ts
Labels: bug, enhancement

#222 "Show qa" button is hidden now if there is no QASession present in lo…
  slidez-fe-core/src/pages/interactive/NoEventPage.tsx
  slidez-fe-core/src/pages/interactive/participant/ParticipantView.tsx
Labels: bug

#227 Added ability to save poll and quiz results
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/State.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/AddReactionEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/StartPollEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/StartQuizEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/StartPollHandler.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/StartQuizEventHandler.java
Labels: bug, enhancement

#230 Fixed ability to vote a couple of times
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionPoll.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionPollAnswer.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQuiz.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQuizAnswer.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/State.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/AnswerPollEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/AnswerQuizEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/AnswerPollHandler.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/AnswerQuizEventHandler.java
  slidez-fe-core/src/common/components/interactive-elements/poll/ParticipantPoll.tsx
  slidez-fe-core/src/containers/session/model/SessionPollAnswer.ts
Labels: bug, enhancement

#221 fix/284-fix_partisipant_page
  slidez-fe-core/src/pages/interactive/participant/ParticipantPage.tsx
  slidez-fe-core/src/pages/interactive/participant/participantPage.scss
Labels: bug

#241 Fixed issue with props validation
  slidez-fe-core/src/pages/interactive/participant/ParticipantReactionButton/index.tsx
Labels: bug

#238 fix/169-Email_and_Password_inputs_are_not_highlighted_in_red
  slidez-fe-core/src/common/components/forms/LoginForm.tsx
Labels: bug

#235 feature/258-Persist_presentation_event_stream_on_backend
  slidez-core/build.gradle
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/SessionService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/DomainEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/HandlerChainHolder.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/sessionEvent/SessionEventRepository.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/sessionEvent/SessionEventService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/sessionEvent/handler/PersistDomainEventInDbHandler.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/sessionEvent/mapper/jsonb/JsonbType.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/sessionEvent/mapper/jsonb/package-info.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/sessionEvent/model/SessionEvent.java
  slidez-core/src/main/resources/db/migration/V17__create_session_event_table.sql
Labels: enhancement

#251 Fixed blinking dashboard issue
  slidez-extension/src/popup/containers/login/redux/authenticationSlice.ts
  slidez-fe-core/src/services/http/http-helper.ts
  slidez-shared/src/net/http/http-helper.ts
Labels: bug

#257 hotfix/add_type_to_option_in_LivePollErrorsProps
  slidez-fe-core/src/containers/poll-editor/PollEditor.tsx
Labels: bug

#258 Implemented default funny names for users. Fixed displaying of modal
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/sessionEvent/handler/PersistDomainEventInDbHandler.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/sessionEvent/mapper/jsonb/JsonbType.java
  slidez-fe-core/src/pages/interactive/Header.tsx
  slidez-fe-core/src/pages/interactive/participant/ParticipantNameModal/ParticipantNameModal.tsx
  slidez-fe-core/src/pages/interactive/participant/ParticipantNameModal/funny-names-service.ts
Labels: bug, enhancement

#262 hotfix/fix_query_in_linkRepository
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/link/LinkRepository.java
Labels: bug

#266 Fixed Q&A like bug
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/HandlerChainHolder.java
  slidez-fe-core/src/containers/session/dto/LikeQuestionDto.ts
  slidez-fe-core/src/containers/session/store/store.ts
Labels: bug

#264 Feature/end interaction on leaving slide
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/State.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/EndInteractionEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/EndInteractionEventHandler.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/HandlerChainHolder.java
  slidez-extension/src/components/slide-iframe/ReactionOverlayFrame.tsx
  slidez-extension/src/present-mode/current-slide-watcher/current-slide-watcher.tsx
  slidez-fe-core/src/common/components/interactive-elements/poll/ParticipantPoll.tsx
  slidez-fe-core/src/containers/session/event/DomainEvent.ts
  slidez-fe-core/src/containers/session/event/FrontendEvent.ts
  slidez-fe-core/src/pages/interactive/presenter/ReactionOverlay/index.tsx
  slidez-shared/src/event-bus/messaging/index.ts
Labels: enhancement

#269 Separate focus-visible pseudo class for Safari
  slidez-fe-core/src/pages/interactive/participant/ParticipantNameModal/styles.module.scss
  slidez-fe-core/src/pages/interactive/participant/participantPage.scss
  slidez-fe-core/src/pages/interactive/participant/participantView.scss
  slidez-fe-core/src/pages/qa/components/QAAdd.scss
Labels: bug
