Repository BinaryStudioAcademy/bsa-2021-slidez, pull requests merged in 2021-08, with the labels that each got.

#18 Feature/18 GitHub actions linters
  .github/workflows/linters.yml
  slidez-core/build.gradle
  slidez-core/src/main/java/com/binarystudio/academy/slidez/SlidezApplication.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/app/root/RootController.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/app/user/UserController.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/infrastructure/healthcheck/HealthchecksController.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/infrastructure/openapi/OpenApiConfig.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/infrastructure/security/SecurityConfig.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/user/UserRepository.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/user/UserService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/user/dto/UserDto.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/user/model/User.java
  slidez-fe-core/package.json
  slidez-fe-core/src/App.tsx
  slidez-fe-core/src/containers/counter/Counter.tsx
  slidez-fe-core/src/containers/counter/counter-service.ts
  slidez-fe-core/src/containers/counter/store.ts
  slidez-fe-core/src/index.tsx
  slidez-fe-core/src/reportWebVitals.ts
  slidez-fe-core/src/store/index.ts
Labels: enhancement, help wanted

#12 #58 setup google slides addon project
  slidez-fe-addon/.claspignore
  slidez-fe-addon/.eslintignore
  slidez-fe-addon/.eslintrc.js
  slidez-fe-addon/.gitignore
  slidez-fe-addon/.npmrc
  slidez-fe-addon/.nvmrc
  slidez-fe-addon/LICENSE
  slidez-fe-addon/README.md
  slidez-fe-addon/appsscript.json
  slidez-fe-addon/dev/.babelrc
  slidez-fe-addon/dev/README.md
  slidez-fe-addon/dev/index.html
  slidez-fe-addon/dev/index.js
  slidez-fe-addon/package-lock.json
  slidez-fe-addon/package.json
  slidez-fe-addon/src/client/.babelrc
  slidez-fe-addon/src/client/README.md
  slidez-fe-addon/src/client/sidebar-add-on/components/About.tsx
  slidez-fe-addon/src/client/sidebar-add-on/index.html
  slidez-fe-addon/src/client/sidebar-add-on/index.tsx
  slidez-fe-addon/src/client/utils/server.js
  slidez-fe-addon/src/server/.babelrc
  slidez-fe-addon/src/server/README.md
  slidez-fe-addon/src/server/index.ts
  slidez-fe-addon/src/server/slides.ts
  slidez-fe-addon/src/server/ui.ts
  slidez-fe-addon/tsconfig.json
  slidez-fe-addon/webpack.config.js
Labels: enhancement

#34 [69] Added env variables to frontend
  .github/workflows/ci.yml
  slidez-fe-core/.env.development
  slidez-fe-core/src/services/auth/auth-service.ts
Labels: enhancement

#38 sync staging properties
  slidez-core/src/main/resources/application-staging.properties
Labels: bug

#66 Added staging env variable
  slidez-core/src/main/resources/application-staging.properties
Labels: bug

#61 fix - Do not scroll header
  slidez-fe-core/src/pages/dashboard/dashboard.scss
Labels: bug

#84 Merge 101-back-login-button
  slidez-fe-core/src/common/components/forms/RegistrationForm.tsx
  slidez-fe-core/src/common/components/forms/sign-form.scss
  slidez-fe-core/src/global/global.scss
Labels: enhancement

#55 Feature/79 client side Poll and PollInput components
  slidez-fe-core/package.json
  slidez-fe-core/src/components/poll/Poll.scss
  slidez-fe-core/src/components/poll/Poll.tsx
  slidez-fe-core/src/components/poll/PollInput.scss
  slidez-fe-core/src/components/poll/PollInput.tsx
  slidez-fe-core/src/components/poll/dto/PollAnswerDto.ts
  slidez-fe-core/src/components/poll/dto/PollDto.ts
  slidez-fe-core/src/components/poll/dto/PollOptionDto.ts
  slidez-fe-core/src/components/poll/dto/pollDtoMock.ts
  slidez-fe-core/yarn.lock
Labels: enhancement

#88 Feature/125 formik and yup
  slidez-core/build.gradle
  slidez-core/src/main/resources/application-example.properties
  slidez-fe-addon/yarn.lock
  slidez-fe-core/package.json
  slidez-fe-core/src/common/components/forms/LoginForm.tsx
  slidez-fe-core/src/common/components/forms/RegistrationForm.tsx
  slidez-fe-core/src/common/components/forms/sign-form.scss
  slidez-fe-core/src/common/components/forms/validation-utils.ts
  slidez-fe-core/yarn.lock
Labels: enhancement

#78 Feature/105 setup mutation observer
  slidez-extension/src/Login.tsx
  slidez-extension/src/login.css
  slidez-extension/src/store/index.ts
  slidez-extension/src/store/reducer.ts
  slidez-fe-core/yarn.lock
  slidez-shared/index.ts
Labels: enhancement

#89 use calc on width header css
  slidez-fe-core/src/pages/dashboard/dashboard.scss
Labels: bug

#97 feature/91-implement-participant-page
  slidez-fe-core/package.json
  slidez-fe-core/src/pages/participant-page/Header.tsx
  slidez-fe-core/src/pages/participant-page/ParticipantPage.tsx
  slidez-fe-core/src/pages/participant-page/header.scss
  slidez-fe-core/src/pages/participant-page/mock-data.ts
  slidez-fe-core/src/pages/participant-page/participantPage.scss
  slidez-fe-core/yarn.lock
Labels: enhancement

#118 Feature/159 render iframe on slides
  slidez-extension/src/Login.tsx
  slidez-extension/src/components/slide-iframe/SlideIframe.scss
  slidez-extension/src/components/slide-iframe/SlideIframe.tsx
  slidez-extension/src/dom/dom-constants.ts
  slidez-extension/src/dom/dom-helpers.ts
  slidez-extension/src/present-mode/current-slide-watcher/current-slide-watcher.tsx
  slidez-extension/src/present-mode/present-mode.ts
  slidez-fe-core/src/App.tsx
  slidez-fe-core/src/common/components/interactive-elements/poll/Poll.scss
  slidez-fe-core/src/common/components/interactive-elements/poll/Poll.tsx
  slidez-fe-core/src/common/components/interactive-elements/poll/PollInput.scss
  slidez-fe-core/src/common/components/interactive-elements/poll/PollInput.tsx
  slidez-fe-core/src/common/components/interactive-elements/poll/dto/PollAnswerDto.ts
  slidez-fe-core/src/common/components/interactive-elements/poll/dto/PollDto.ts
  slidez-fe-core/src/common/components/interactive-elements/poll/dto/PollOptionDto.ts
  slidez-fe-core/src/common/components/interactive-elements/poll/dto/pollDtoMock.ts
Labels: enhancement

#114 Feature/137-set user data(top right corner as real data)
  slidez-fe-core/src/pages/dashboard/Dashboard.tsx
  slidez-fe-core/src/pages/dashboard/UserProfile.tsx
Labels: enhancement

#126 fit/164-fix-position-the-user-profile-logo
  slidez-fe-core/src/pages/dashboard/dashboard.scss
Labels: bug

#123 fix imports after mode methods
  slidez-fe-core/src/App.tsx
  slidez-fe-core/src/pages/dashboard/UserProfile.tsx
Labels: bug

#122 Fix/148 161 fix search functionatity
  slidez-fe-core/src/assets/svgs/clear-text-in-search.svg
  slidez-fe-core/src/pages/dashboard/Dashboard.tsx
  slidez-fe-core/src/pages/dashboard/dashboard.scss
Labels: bug

#128 fix view switch
  slidez-fe-core/src/pages/dashboard/Dashboard.tsx
Labels: Approved

#127 fix grid size
  slidez-fe-core/src/pages/dashboard/dashboard.scss
Labels: Approved

#131 Fix/173 update sidebar icons
  slidez-fe-core/src/assets/svgs/create_presentation.svg
  slidez-fe-core/src/assets/svgs/graph_icon.svg
  slidez-fe-core/src/assets/svgs/layout_icon.svg
  slidez-fe-core/src/assets/svgs/my_presentation.svg
  slidez-fe-core/src/pages/dashboard/SideBar.tsx
  slidez-fe-core/src/pages/dashboard/dashboard.scss
Labels: Approved

#142 Feature/186 correct login page addon
  slidez-fe-core/src/common/components/forms/sign-form.scss
  slidez-fe-core/src/pages/sign/styles.module.scss
Labels: enhancement

#162 Feature/qa session backend
  slidez-core/src/main/java/com/binarystudio/academy/slidez/app/qasession/QASessionController.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/app/qasession/QASessionResponseCodes.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/app/session/SessionResponseCodes.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/poll/PollService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/poll/model/Poll.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/presentation/PresentationService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/qasession/QASessionRepository.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/qasession/QASessionService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/qasession/dto/CreateQASessionDto.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/qasession/exception/QASessionNotFoundException.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQAQuestion.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQASession.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/State.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/enums/ResponseType.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/AskQuestionEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/StartQASessionEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/AskQuestionEventHandler.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/HandlerChainHolder.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/StartQASessionHandler.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/mapper/SessionInteractiveElementMapper.java
Labels: enhancement

#163 Feature/quiz backend
  slidez-core/src/main/java/com/binarystudio/academy/slidez/app/quiz/QuizController.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/app/quiz/QuizResponseCodes.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/app/session/SessionResponseCodes.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/poll/mapper/PollMapper.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/quiz/QuizRepository.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/quiz/QuizService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/quiz/dto/CreateQuizAnswersDto.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/quiz/dto/CreateQuizDto.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/quiz/exception/QuizNotFoundException.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/quiz/mapper/QuizMapper.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/quiz/model/Quiz.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionPoll.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQuiz.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQuizAnswer.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/SessionQuizOption.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/data/State.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/enums/ResponseType.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/AnswerQuizEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/event/StartQuizEvent.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/AnswerQuizEventHandler.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/HandlerChainHolder.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/handler/StartQuizEventHandler.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/session/mapper/SessionInteractiveElementMapper.java
Labels: enhancement

#164 Fix the new poll adding
  slidez-fe-addon/src/server/slides.ts
Labels: bug

#160 Fix/202 restyle qa page
  slidez-fe-core/src/assets/svgs/like.svg
  slidez-fe-core/src/common/components/interactive-elements/q-and-a/QandA.tsx
  slidez-fe-core/src/common/components/interactive-elements/q-and-a/header/QandAHeader.tsx
  slidez-fe-core/src/common/components/interactive-elements/q-and-a/header/q-and-a-header.scss
  slidez-fe-core/src/common/components/interactive-elements/q-and-a/q-and-a.scss
  slidez-fe-core/src/common/components/interactive-elements/q-and-a/question/Question.tsx
  slidez-fe-core/src/common/components/interactive-elements/q-and-a/question/question.scss
  slidez-fe-core/src/common/components/interactive-elements/q-and-a/styles.qa.scss
Labels: enhancement

#155 Fix/170 171 fix user profile
  slidez-core/src/main/java/com/binarystudio/academy/slidez/app/user/UserController.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/user/UserService.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/user/dto/UserPasswordRequest.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/user/dto/UserPasswordResponse.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/user/mapper/UserMapper.java
  slidez-core/src/main/java/com/binarystudio/academy/slidez/domain/userprofile/UserProfile.java
  slidez-fe-core/src/App.tsx
  slidez-fe-core/src/common/routes/app-route.ts
  slidez-fe-core/src/containers/user-menu/UserMenu.tsx
  slidez-fe-core/src/containers/user-menu/edit-profile/Field.tsx
  slidez-fe-core/src/containers/user-menu/edit-profile/components/Form.scss
  slidez-fe-core/src/containers/user-menu/edit-profile/components/FormUpdatePassword.tsx
  slidez-fe-core/src/containers/user-menu/edit-profile/components/FormUpdateUserData.tsx
  slidez-fe-core/src/containers/user-menu/edit-profile/components/Loader.scss
  slidez-fe-core/src/containers/user-menu/edit-profile/components/Loader.tsx
  slidez-fe-core/src/containers/user-menu/edit-profile/components/UpdatePasswordErrors.tsx
  slidez-fe-core/src/containers/user-menu/edit-profile/components/UpdateUserProfileErrors.tsx
  slidez-fe-core/src/containers/user-menu/edit-profile/editProfileTypes.ts
  slidez-fe-core/src/containers/user-menu/edit-profile/validations.ts
  slidez-fe-core/src/containers/user-menu/handleLogo.ts
  slidez-fe-core/src/containers/user-menu/styles.module.scss
  slidez-fe-core/src/containers/user/store.ts
  slidez-fe-core/src/pages/dashboard/Dashboard.tsx
  slidez-fe-core/src/pages/dashboard/styles.module.scss
  slidez-fe-core/src/pages/update/UpdatePage.tsx
  slidez-fe-core/src/pages/update/update.scss
  slidez-fe-core/src/services/auth/auth-service.ts
  slidez-fe-core/src/services/auth/dto/TokenDto.ts
  slidez-fe-core/src/services/user/dto/UpdatePasswordRequest.ts
  slidez-fe-core/src/services/user/dto/UpdatePasswordResponse.ts
  slidez-fe-core/src/services/user/dto/UpdateProfileDto.ts
  slidez-fe-core/src/services/user/dto/UpdateResult.ts
  slidez-fe-core/src/services/user/user-service.ts
Labels: bug, enhancement
